services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medium_clone
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8030:8080"
    depends_on:
      postgres:
        condition: service_healthy
