import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LocalizedStringProvider } from "react-aria-components/i18n";
import Header from "~/components/Header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <LocalizedStringProvider locale="en" />
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
