import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalizedStringProvider } from "react-aria-components/i18n";
import Header from "~/components/Header";
import Footer from "~/components/Footer";
import { styles } from "~/styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div id="app" className={styles.app}>
          <LocalizedStringProvider locale="en" />
          <Header />

          <div className={styles.main}>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
